# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Loyw8-Bt7sUJ3SOalxvS7VoB7igM-VoA
"""

import pandas as pd
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.inference import VariableElimination


def create_dataset():
    return pd.DataFrame({
        'Rain': ['No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'Yes', 'No'],
        'TrafficJam': ['Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'No', 'No'],
        'ArriveLate': ['Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No']
    })


def build_model():
    return DiscreteBayesianNetwork([
        ('Rain', 'TrafficJam'),
        ('TrafficJam', 'ArriveLate')
    ])


def train_model(model, data):
    model.fit(data)
    return model


def display_cpds(model):
    print("\nLearned CPDs:\n")
    for cpd in model.get_cpds():
        print(cpd)


def perform_inference(model):
    inference = VariableElimination(model)
    result = inference.query(
        variables=['ArriveLate'],
        evidence={'Rain': 'Yes'}
    )
    return result


def main():
    data = create_dataset()
    model = build_model()
    model = train_model(model, data)

    display_cpds(model)

    result = perform_inference(model)
    print("\nInference Result (P(ArriveLate | Rain=Yes)):\n")
    print(result)


if __name__ == "__main__":
    main()